example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('wishlist/', include('wishlist.urls')),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import show_wishlist
from wishlist.views import show_xml
from wishlist.views import show_json
from wishlist.views import show_xml_by_id
from wishlist.views import show_json_by_id
from wishlist.views import register
from wishlist.views import login_user
from wishlist.views import logout_user
from wishlist.views import show_wishlist_ajax
from wishlist.views import add_wishlist

app_name = 'wishlist'

urlpatterns = [
    path('', show_wishlist, name='show_wishlist'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<int:id>', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('ajax/', show_wishlist_ajax, name='show_wishlist_ajax'),
    path('ajax/add-wishlist/', add_wishlist, name='add_wishlist'),
]

example_app/models.py
from django.db import models

# Create your models here.

wishlist/models.py
from django.db import models

# Create your models here.
class BarangWishlist(models.Model):
    nama_barang = models.CharField(max_length=50)
    harga_barang = models.IntegerField()
    deskripsi = models.TextField()
    

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

wishlist/views.py
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import render
from wishlist.models import BarangWishlist
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

# Create your views here.
@login_required(login_url='/wishlist/login/')
def show_wishlist(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Mayfa Shadrina Siddi',
        'last_login' : request.COOKIES['last_login'],
    }
    return render(request, "wishlist.html", context)

def show_xml(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("xml", data_barang_wishlist), content_type="application/xml")

def show_json(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    return HttpResponse(serializers.serialize("json", data_barang_wishlist), content_type="application/json")

def show_xml_by_id(request, id):
    data_barang_wishlist = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data_barang_wishlist), content_type="application/xml")

def show_json_by_id(request, id):
    data_barang_wishlist = BarangWishlist.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data_barang_wishlist), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('wishlist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("wishlist:show_wishlist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('wishlist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/wishlist/login/')
def show_wishlist_ajax(request):
    data_barang_wishlist = BarangWishlist.objects.all()
    context = {
        'list_barang': data_barang_wishlist,
        'nama': 'Mayfa Shadrina Siddi',
        'last_login' : request.COOKIES['last_login'],
    }
    return render(request, "wishlist_ajax.html", context)

@login_required(login_url='/wishlist/login/')
def add_wishlist(request):
    if request.method == 'POST':
        nama_barang = request.POST.get('username')
        harga_barang = request.POST.get('password')
        deskripsi = request.POST.get('password')
        item = BarangWishlist(nama_barang=nama_barang, harga_barang=harga_barang, deskripsi=deskripsi)
        item.save()
        return JsonResponse({"instance": "Proyek Dibuat"}, status=200)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>

</html>

wishlist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
        
    Belum mempunyai akun? <a href="{% url 'wishlist:register' %}">Buat Akun</a>

</div>

{% endblock content %}

wishlist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <h1>Formulir Registrasi</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

wishlist/templates/wishlist.html
{% extends 'base.html' %}
{% block content %}
<style>
    table {
        text-align: center;
        margin-left: auto;  
        margin-right: auto; 
    }
</style>

{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <div class="d-grid gap-3">
        <nav class="navbar bg-success">
            <div class="container-fluid">
            <span class="navbar-brand text-light h1">Tokopetantang</span>
            <li class="nav-item dropdown no-bullets">
                <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{nama}}
                </a>
                <ul class="dropdown-menu">
                    <a class="dropdown-item" href="#">Profile</a>
                    <a class="dropdown-item" href="#">Pendapatan</a>
                    <a class="dropdown-item" href="#">Pengeluaran</a>
                    <hr class="dropdown-divider">
                    <a class="dropdown-item text-success" href="{% url 'wishlist:logout' %}">Log Out</a>
                </ul>
            </li>
            </div>
        </nav>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
        <div class="d-flex justify-content-center">
            <h4>Daftar Barang Toko Mae</h4>
        </div>

        <table>
            <table class="table table-striped", style="width: 50%", .padding:"center">
            <tr>
            <th class="text-success">Nama Barang</th>
            <th class="text-success">Harga Barang</th>
            <th class="text-success">Deskripsi</th>
            </tr>
            <tbody class="table-group-divider">

            {% comment %} Tambahkan data di bawah baris ini {% endcomment %}
            {% for barang in list_barang %}
            <tr>
                <th class=" fw-normal">{{barang.nama_barang}}</th>
                <th class=" fw-normal">{{barang.harga_barang}}</th>
                <th class=" fw-normal">{{barang.deskripsi}}</th>
            </tr>
            {% endfor %}
        </table>
        <div class="d-flex justify-content-center">
            <th class=" fw-normal">Sesi terakhir login: {{ last_login }}</th>
        </div>

    </div>
  </body>
</html>
{% endblock content%}

wishlist/templates/wishlist_ajax.html
{% extends 'base.html' %}
{% block content %}
<style>
    table {
        text-align: center;
        margin-left: auto;  
        margin-right: auto; 
    }
</style>

{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
</head>
  <body>
    <div class="d-grid gap-3">
        <nav class="navbar bg-success">
            <div class="container-fluid">
            <span class="navbar-brand text-light h1">Tokopetantang</span>
            <li class="nav-item dropdown no-bullets">
                <a class="nav-link dropdown-toggle text-light" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                {{nama}}
                </a>
                <ul class="dropdown-menu">
                    <a class="dropdown-item" href="#">Profile</a>
                    <a class="dropdown-item" href="#">Pendapatan</a>
                    <a class="dropdown-item" href="#">Pengeluaran</a>
                    <hr class="dropdown-divider">
                    <a class="dropdown-item text-success" href="{% url 'wishlist:logout' %}">Log Out</a>
                </ul>
            </li>
            </div>
        </nav>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
        <div class="d-flex justify-content-center">
            <h4>Daftar Barang Toko Mae</h4>
        </div>

        <div>
            <form method="POST" action="" id="formtable" class="d-flex justify-content-center p-2">
              <div class="bg-danger d-flex justify-content-center p-2 rounded-2 p-3">
                {% csrf_token %}
                <table>
                  <tr>
                      <td>Nama Barang: </td>
                      <td><input type="text" name="nama_barang" placeholder="Nama Barang" class="form-control" id="nama_barang"></td>
                  </tr>
                  <tr>
                      <td>Harga Barang: </td>
                      <td><input type="text" name="harga_barang" placeholder="Harga Barang" class="form-control" id="harga_barang"></td>
                  </tr>
                  <tr>
                      <td>Deskripsi: </td>
                      <td><input type="text" name="deskripsi" placeholder="Deskripsi" class="form-control" id="deskripsi"></td>
                  </tr>
                  
                  
                  </table>
                  <button onclick="clickCounter()" type="submit" id="masuk" class="btn border rounded bg-info mx-2">Tambah</button>
              </div>
            
              
            </form>
        </div> 
        <div class="d-flex justify-content-center">
            <th class=" fw-normal">Sesi terakhir login: {{ last_login }}</th>
        </div>

    </div>
  </body>
</html>

<script>
    let tab;
    function loadData() {
        $.get("{% url 'wishlist:show_json' %}", function(data) {
            tab = `<tr>
            <th class="text-success">Nama Barang</th>
            <th class="text-success">Harga Barang</th>
            <th class="text-success">Deskripsi</th>
            </tr> `;

        for (let item of data) {
            tab += `<tr>
                <th class=" fw-normal">{{barang.nama_barang}}</th>
                <th class=" fw-normal">{{barang.harga_barang}}</th>
                <th class=" fw-normal">{{barang.deskripsi}}</th>
            </tr>`;}
        
            document.getElementById("add_wishlist").innerHTML = tab;
        });
    }

    $(document).read(function()) {
        loadData();
    });

    $(document).on("add-wishlist", "#formtable", function (e)) {
        e.preventDefault();
        $.ajax({
            type: "POST",
            url: "{% url 'wishlist:add_wishlist' %}",
            data: {
                nama_barang: $("#nama_barang").val(),
                harga_barang: $("#harga_barang").val(),
                deskripsi: $("#deskripsi").val(),
                csrfmiddlewaretoken: "{{ csrf_token }}",
            },
            dataType: "json",
            success: function() {
                loadData();
            },
        });
    });

    function clickCOunter() {
        if (localStorage.clickcount) {
            localStorage.clickcount = Number(localStorage.clickcount)+1;
        } else {
            localStorage.clickcount = 1;
        }
    }
</script>
{% endblock content%}